import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { SocketProvider } from '@/context/SocketContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'HTX - Admin Panel',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<StoreProvider>
					<SocketProvider>{children}</SocketProvider>
				</StoreProvider>
				<ToastContainer />
			</body>
		</html>
	);
}
